In [2]:
# QUESTION 10
import numpy as np
A = np.array([[1, 2, -2], [1, 1, 9], [0, 1, 9]])
x0 = np.array([1, 0, 0])

def powermat(A, x0, nit):
    x = x0
    for _ in range(nit+1):
        xnew = A.dot(x)
        lambda_ = np.linalg.norm(xnew, np.inf)/np.linalg.norm(x, np.inf)
        x = xnew

    x = x/np.linalg.norm(x, np.inf)

    return x, lambda_

print(powermat(A, x0, 5))
print(powermat(A, x0, 6))

(array([0.00377789, 1.        , 0.99815498]), 9.93193717277487)
(array([7.47752344e-04, 1.00000000e+00, 9.99621725e-01]), 9.987172728870146)


In [3]:
# QUESTION 12
A = np.array([[-3, 2], [2, 0]])
x0 = np.array([1, 0])

def rayleigh(A, x0, nit):
    x = x0
    for _ in range(nit):
        xnew = A.dot(x)
        lambda_ = xnew.dot(x)/x.dot(x)
        x = xnew

    x = x/np.linalg.norm(x, np.inf)

    return x, lambda_

for i in range(1, 5):
    rq = rayleigh(A, x0, i)
    power = powermat(A, x0, i)
    print(power, rq[1])



(array([ 1.        , -0.46153846]), 4.333333333333333) -3.0
(array([-1.        ,  0.50980392]), 3.923076923076923) -3.923076923076923
(array([ 1.        , -0.49756098]), 4.019607843137255) -3.995121951219512
(array([-1.       ,  0.5006105]), 3.995121951219512) -3.9996948428440646


In [13]:
# QUESTION 18
A = np.array([[8, 0, 12], [1, -2, 1], [0, 3, 0]])
x0 = np.array([1, 0, 0])

def inverse_power_method(A, alpha, x, tol=1e-8, max_iter=10):

    
    for _ in range(max_iter):
        y = np.linalg.solve(A - alpha * np.eye(A.shape[0]), x)
        j = np.argmax(np.abs(y))
        v = alpha + (1.0 / y[j])
        x = (1.0 / y[j]) * y
    
    return v, x

res = inverse_power_method(A, -1.4, x0)
print(res[0])
print(res[1])

-1.4244289008983873
[ 1.          0.3729008  -0.78536908]
